import { Trip } from "@/types";

export const DEMO_TRIP: Trip = {
  id: "demo-tokyo-2024",
  title: "Tokyo: Neon, Ramen & Sakura",
  destination: ["Tokyo", "Kyoto"],
  startDate: "2024-04-01",
  endDate: "2024-04-07",
  travelers: 2,
  vibes: ["foodie", "cultural", "adventure"],
  budget: { total: 3200, currency: "USD" },
  pace: "balanced",
  createdAt: Date.now(),
  updatedAt: Date.now(),
  collaborators: [],
  days: [
    {
      id: "day-1",
      dayNumber: 1,
      date: "2024-04-01",
      city: "Tokyo",
      weather: { tempC: 16, condition: "Partly Cloudy", icon: "⛅" },
      energyScore: "balanced",
      notes: "First day! Take it easy — jetlag is real. Stick to Shibuya/Shinjuku.",
      activities: [
        {
          id: "act-1-1",
          type: "lodging",
          name: "Check-in: Park Hyatt Tokyo",
          description: "The legendary hotel from Lost in Translation. Park Hyatt Tokyo sits on floors 39–52 of the Shinjuku Park Tower.",
          reasoning: "Central Shinjuku location, world-class service, and unforgettable skyline views.",
          startTime: "15:00",
          durationMin: 60,
          location: { lat: 35.6858, lng: 139.6916, address: "3-7-1-2 Nishi Shinjuku, Shinjuku City", neighborhood: "Shinjuku" },
          cost: { amount: 450, currency: "USD", perPerson: false },
          bookingUrl: "https://www.hyatt.com/park-hyatt/en-US/tyoph-park-hyatt-tokyo",
          photos: [],
          tags: ["luxury", "iconic", "views"],
          votes: [],
          comments: [],
          alternatives: [],
        },
        {
          id: "act-1-2",
          type: "experience",
          name: "Shibuya Scramble Crossing at Dusk",
          description: "The world's busiest pedestrian crossing — 3,000 people cross at once. Mesmerizing at sunset and electric at night.",
          reasoning: "No Tokyo trip is complete without this. The energy is infectious, especially as city lights flicker on.",
          startTime: "17:30",
          durationMin: 45,
          location: { lat: 35.6595, lng: 139.7004, address: "Shibuya Crossing, Shibuya City", neighborhood: "Shibuya" },
          cost: { amount: 0, currency: "USD", perPerson: false },
          photos: [],
          tags: ["iconic", "free", "photography"],
          votes: [],
          comments: [],
          alternatives: [],
        },
        {
          id: "act-1-3",
          type: "food",
          name: "Ichiran Ramen — Shibuya",
          description: "Solo ramen booths designed for pure, distraction-free noodle communion. Order the Hakata-style tonkotsu with extra richness.",
          reasoning: "The solo booth concept is a quintessential Tokyo experience. Perfect for tired travellers who want great food without social energy.",
          startTime: "19:30",
          durationMin: 60,
          location: { lat: 35.6587, lng: 139.6986, address: "1-22-7 Jinnan, Shibuya City", neighborhood: "Shibuya" },
          cost: { amount: 15, currency: "USD", perPerson: true },
          bookingUrl: "https://en.ichiran.com",
          photos: [],
          tags: ["ramen", "foodie", "solo-dining"],
          votes: [],
          comments: [],
          alternatives: [],
        },
      ],
    },
    {
      id: "day-2",
      dayNumber: 2,
      date: "2024-04-02",
      city: "Tokyo",
      weather: { tempC: 18, condition: "Sunny", icon: "☀️" },
      energyScore: "packed",
      notes: "Full cultural immersion day — Asakusa in the morning, Akihabara by afternoon.",
      activities: [
        {
          id: "act-2-1",
          type: "food",
          name: "Tsukiji Outer Market Breakfast",
          description: "Fresh tamagoyaki, sea urchin on rice, and tamago sushi at the oldest fish market stalls in Japan.",
          reasoning: "Best breakfast in Tokyo, hands down. Arrive before 9am to beat crowds.",
          startTime: "08:00",
          durationMin: 90,
          location: { lat: 35.6653, lng: 139.7707, address: "4-16-2 Tsukiji, Chuo City", neighborhood: "Tsukiji" },
          cost: { amount: 20, currency: "USD", perPerson: true },
          photos: [],
          tags: ["breakfast", "seafood", "market"],
          votes: [],
          comments: [],
          alternatives: [],
        },
        {
          id: "act-2-2",
          type: "sight",
          name: "Senso-ji Temple & Nakamise-dori",
          description: "Tokyo's oldest temple, built in 645 AD. Walk through the iconic Kaminarimon gate and browse 200 traditional craft shops.",
          reasoning: "The sakura in Asakusa in April is breathtaking. This is the cultural heart of old Edo.",
          startTime: "10:00",
          durationMin: 120,
          location: { lat: 35.7148, lng: 139.7967, address: "2-3-1 Asakusa, Taito City", neighborhood: "Asakusa" },
          cost: { amount: 0, currency: "USD", perPerson: false },
          photos: [],
          tags: ["temple", "history", "sakura", "free"],
          votes: [],
          comments: [],
          alternatives: [],
        },
        {
          id: "act-2-3",
          type: "experience",
          name: "TeamLab Planets — Digital Art Immersion",
          description: "Walk through water, lose yourself in infinite crystal universes, and become part of living digital art.",
          reasoning: "One of the most visually spectacular experiences on Earth. Book in advance — it sells out weeks ahead.",
          startTime: "14:00",
          durationMin: 120,
          location: { lat: 35.6451, lng: 139.7834, address: "6-1-16 Toyosu, Koto City", neighborhood: "Toyosu" },
          cost: { amount: 32, currency: "USD", perPerson: true },
          bookingUrl: "https://planets.teamlab.art/tokyo/",
          photos: [],
          tags: ["art", "immersive", "instagram"],
          votes: [],
          comments: [],
          alternatives: [],
        },
        {
          id: "act-2-4",
          type: "food",
          name: "Yakitori under the Yurakucho Tracks",
          description: "Tiny izakayas tucked under the train tracks, smoke-filled with grilling chicken skewers and cold Sapporo.",
          reasoning: "This is the soul of Tokyo nightlife — working-class, authentic, and impossibly atmospheric.",
          startTime: "19:00",
          durationMin: 120,
          location: { lat: 35.6748, lng: 139.7622, address: "Yurakucho, Chiyoda City", neighborhood: "Yurakucho" },
          cost: { amount: 35, currency: "USD", perPerson: true },
          photos: [],
          tags: ["yakitori", "izakaya", "nightlife"],
          votes: [],
          comments: [],
          alternatives: [],
        },
      ],
    },
    {
      id: "day-3",
      dayNumber: 3,
      date: "2024-04-03",
      city: "Tokyo",
      weather: { tempC: 15, condition: "Light Rain", icon: "🌧" },
      energyScore: "light",
      notes: "Rain day — perfect for museums, bookshops, and coffee.",
      activities: [
        {
          id: "act-3-1",
          type: "sight",
          name: "teamLab Borderless — Mori Building",
          description: "Over 60 immersive artworks that know no boundaries — artworks move, influence and mingle.",
          reasoning: "Rain makes outdoor sightseeing tough. This immersive indoor museum is a perfect fit.",
          startTime: "10:00",
          durationMin: 180,
          location: { lat: 35.6628, lng: 139.7316, address: "1-3-8 Azabudai, Minato City", neighborhood: "Azabudai Hills" },
          cost: { amount: 38, currency: "USD", perPerson: true },
          photos: [],
          tags: ["art", "museum", "indoor"],
          votes: [],
          comments: [],
          alternatives: [],
        },
        {
          id: "act-3-2",
          type: "food",
          name: "Kissaten Coffee Culture — Café de l'Ambre",
          description: "Founded in 1948, this legendary kissaten in Ginza serves aged single-origin coffee with ritualistic precision.",
          reasoning: "A rainy afternoon in a 70-year-old Tokyo coffee house is pure poetry.",
          startTime: "14:00",
          durationMin: 60,
          location: { lat: 35.6712, lng: 139.7648, address: "8-10-15 Ginza, Chuo City", neighborhood: "Ginza" },
          cost: { amount: 8, currency: "USD", perPerson: true },
          photos: [],
          tags: ["coffee", "vintage", "relaxed"],
          votes: [],
          comments: [],
          alternatives: [],
        },
      ],
    },
  ],
  logistics: {
    visa: "Most Western passport holders get a free 90-day tourist visa on arrival. No pre-approval needed.",
    currency: { code: "JPY", rateToUSD: 149.5 },
    powerPlug: "Type A (same as USA). Japan uses 100V — most modern electronics handle this fine.",
    tipping: "Tipping is NOT customary in Japan and can even be seen as rude. Never tip at restaurants, taxis, or hotels.",
    transport: "Get a Suica IC card at the airport — it works on all trains, subways, and convenience stores. 7-day JR Pass is worth it if going to Kyoto.",
    simCard: "Get an IIJmio or Mobal SIM at the airport. Unlimited data from ¥3,500/month.",
    phrases: [
      { en: "Thank you", local: "ありがとうございます", phonetic: "Arigatou gozaimasu" },
      { en: "Excuse me / Sorry", local: "すみません", phonetic: "Sumimasen" },
      { en: "Where is...?", local: "〜はどこですか？", phonetic: "~ wa doko desu ka?" },
      { en: "How much?", local: "いくらですか？", phonetic: "Ikura desu ka?" },
      { en: "One beer please", local: "ビールを一本ください", phonetic: "Biiru wo ippon kudasai" },
    ],
    vaccinations: ["No mandatory vaccinations", "Hepatitis A recommended", "Japanese Encephalitis if hiking rural areas"],
    emergencyNumbers: [
      { label: "Police", number: "110" },
      { label: "Fire / Ambulance", number: "119" },
      { label: "Japan Helpline (English)", number: "0570-000-911" },
    ],
    embassy: {
      address: "1-10-5 Akasaka, Minato-ku, Tokyo 107-8420",
      phone: "+81-3-3224-5000",
    },
  },
  packingList: [
    { id: "pl-1", name: "Passport + visa printout", category: "Documents", checked: false },
    { id: "pl-2", name: "JR Pass (pre-purchased)", category: "Documents", checked: false },
    { id: "pl-3", name: "Travel insurance docs", category: "Documents", checked: false },
    { id: "pl-4", name: "Lightweight rain jacket", category: "Clothing", checked: false },
    { id: "pl-5", name: "Slip-on shoes (temples require removal)", category: "Clothing", checked: false },
    { id: "pl-6", name: "Layering shirts", category: "Clothing", checked: false },
    { id: "pl-7", name: "Power adapter (Type A)", category: "Tech", checked: false },
    { id: "pl-8", name: "Portable battery pack", category: "Tech", checked: false },
    { id: "pl-9", name: "Pocket WiFi or Japan SIM card", category: "Tech", checked: false },
    { id: "pl-10", name: "Sunscreen SPF 50+", category: "Toiletries", checked: false },
    { id: "pl-11", name: "Allergy medication", category: "Medication", checked: false },
    { id: "pl-12", name: "Foldable tote bag (convenience store finds)", category: "Activity-specific", checked: false },
  ],
};
